### ISSUE TITLE
Use NPM for distribution

### ISSUE THREAD

**Issue by chemerisuk** [chemerisuk/better-dom#36]
The world started to use NPM for front-end dependencies. And I believe this is a good thing.

http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick
http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm
https://github.com/npm-examples/using-jquery-plugins-global

**Comment by lordgiotto** [comment]
Completely agree :) I would love to require it directly with browserify!

**Comment by chemerisuk** [comment]
Version 3.0.0-beta.2 is [available](https://www.npmjs.com/package/better-dom) in NPM.
