### ISSUE TITLE
nasty error message in manipulation module

### ISSUE THREAD

**Issue by marcorra** [chemerisuk/better-dom#37]
I was reading the documentation about the append(). It stands it can handle array ( [] ). So i tried this:

link.append( [elem, elem] );

and

link.append( [string, string] );

If you try, you will see it throws a nasty message. I figured out you was meaning

link.append( elem, elem );

but for me this is not an array. 

I'm writing fast on my mobile now, so I know bad format on this issue.

**Comment by chemerisuk** [comment]
@marcorra true, only array of elements is supported for now. For array of strings call `.join()` to get the final string that can be used in manipulation methods.

**Comment by marcorra** [comment]
@chemerisuk Got it. But seems like there are some bugs for appending function content too. It throws both for insertAdjacentHTML and the normal way.

**NoModificationAllowedError: Modifications are not allowed for this document**

**HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy**

**Comment by chemerisuk** [comment]
@marcorra could you give me HTML fragment and code that you use? Also, what's the browser version?

**Comment by marcorra** [comment]
@chemerisuk  Sorry, but I'm not home now, so can't send you HTML. But I can do better...
This errors occur only on the root node - document, and with method 'after' and before. At least what I tested for. append and prepend seems to work.

Will throw:
DOM.before(function(node) {
return node.get('className');
});
Will not throw:
DOM.query('body').before(function(node) {
return node.get('className');
});

Again sorry for bad text format here, and there are probably a few other bugs here, but couldn't find them now. At least I tracked this one.

**Comment by chemerisuk** [comment]
Well, `DOM` is referring the `<html>` element, therefore if you are trying to add an element after it, your `document` does not allow that. Not sure if I should handle that situation in the library.

**Comment by marcorra** [comment]
@chemerisuk Sorry late reply. I tend to agree. I think there is no point in fixing it. I checked around. Even jQuery and angularJS are throwing errors on the same place. jQuery say that 'context not found' when creating documentFragment. 

It should be an easy fix anyway, check if 'this' is equal to DOM and return 'this' if methodName is equal to before or after.

**Comment by chemerisuk** [comment]
@marcorra I think better to keep it as it is: developer should have an error in case he or she is doing something wrong, like in this case.
